name: Run Python Tests
on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test123
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgresql
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      - name: Create DB and Table
        run: |
          psql \
          -d "postgresql://postgresql:test123@localhost/test?sslmode=disable" \
          -c "CREATE TABLE metrics (id serial NOT NULL PRIMARY KEY, url TEXT, http_status TEXT, day TEXT, month TEXT, year TEXT, time TEXT,elapsed_time TEXT, pattern_verified TEXT);"
        env:
          PGPASSWORD: postgres_password
      - name: Run tests and Run Coverage
        run: |
          pip install coverage
          coverage run -m unittest tests/all_tests.py
          coverage xml
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}